# AWS Configuration
# AWS服务相关配置

aws:
  # 区域设置
  region: us-east-1
  
  # Bedrock配置
  bedrock:
    # Nova模型配置
    nova:
      model_id: amazon.nova-lite-v1:0
      max_tokens: 2048
      temperature: 0.7
      top_p: 0.9
    
    # Titan Embedding配置
    titan:
      model_id: amazon.titan-embed-text-v2:0
      dimension: 1024
      batch_size: 10
  
  # S3配置
  s3:
    bucket_name: ${S3_BUCKET}
    prefix: documents/
    max_file_size: 10485760  # 10MB
    allowed_types:
      - .pdf
      - .txt
      - .md
  
  # Lambda配置
  lambda:
    function_name: rag-query-handler
    timeout: 300  # 5分钟
    memory_size: 3008  # MB
    
  # API Gateway配置
  api_gateway:
    stage: prod
    throttle_rate: 100
    throttle_burst: 200