# Database Configuration
# Zilliz Cloud向量数据库配置

zilliz:
  # 连接配置
  connection:
    endpoint: ${ZILLIZ_ENDPOINT}
    token: ${ZILLIZ_TOKEN}
    timeout: 30  # 秒
    
  # 集合配置
  collection:
    name: rag_collection
    dimension: 1024  # Titan Embedding维度
    
  # 索引配置
  index:
    type: IVF_FLAT
    metric_type: L2  # 欧式距离
    params:
      nlist: 1024
      nprobe: 10
    
  # 搜索配置
  search:
    default_top_k: 5
    max_top_k: 100
    score_threshold: 0.5
    
  # 性能配置
  performance:
    batch_size: 100
    auto_flush: true
    flush_interval: 5  # 秒
    
  # 备份配置
  backup:
    enabled: false
    interval: 86400  # 24小时
    retention_days: 7